controller_list:
  - name: fake_Arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_01_joint_06
      - arm_01_joint_05
      - arm_01_joint_04
      - arm_01_joint_03
      - arm_01_joint_02
      - arm_01_joint_01
  - name: fake_Arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_02_joint_06
      - arm_02_joint_05
      - arm_02_joint_04
      - arm_02_joint_03
      - arm_02_joint_02
      - arm_02_joint_01
  - name: fake_Arm_3_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_03_joint_06
      - arm_03_joint_05
      - arm_03_joint_04
      - arm_03_joint_03
      - arm_03_joint_02
      - arm_03_joint_01
  - name: fake_Arm1_and_Arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_01_joint_06
      - arm_01_joint_05
      - arm_01_joint_04
      - arm_01_joint_03
      - arm_01_joint_02
      - arm_01_joint_01
      - arm_02_joint_06
      - arm_02_joint_05
      - arm_02_joint_04
      - arm_02_joint_03
      - arm_02_joint_02
      - arm_02_joint_01
initial:  # Define initial robot poses per group
  - group: Arm1_and_Arm2
    pose: home_pose