Arm_1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_01_joint_06
    - arm_01_joint_05
    - arm_01_joint_04
    - arm_01_joint_03
    - arm_01_joint_02
    - arm_01_joint_01
  gains:
    arm_01_joint_06:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Arm_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_02_joint_06
    - arm_02_joint_05
    - arm_02_joint_04
    - arm_02_joint_03
    - arm_02_joint_02
    - arm_02_joint_01
  gains:
    arm_02_joint_06:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Arm_3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_03_joint_06
    - arm_03_joint_05
    - arm_03_joint_04
    - arm_03_joint_03
    - arm_03_joint_02
    - arm_03_joint_01
  gains:
    arm_03_joint_06:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_03_joint_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_03_joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_03_joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_03_joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_03_joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Arm1_and_Arm2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_01_joint_06
    - arm_01_joint_05
    - arm_01_joint_04
    - arm_01_joint_03
    - arm_01_joint_02
    - arm_01_joint_01
    - arm_02_joint_06
    - arm_02_joint_05
    - arm_02_joint_04
    - arm_02_joint_03
    - arm_02_joint_02
    - arm_02_joint_01
  gains:
    arm_01_joint_06:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_01_joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_06:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_02_joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1