controller_list:
  - name: Arm_1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_01_joint_06
      - arm_01_joint_05
      - arm_01_joint_04
      - arm_01_joint_03
      - arm_01_joint_02
      - arm_01_joint_01
  - name: Arm_2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_02_joint_06
      - arm_02_joint_05
      - arm_02_joint_04
      - arm_02_joint_03
      - arm_02_joint_02
      - arm_02_joint_01
  - name: Arm_3_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_03_joint_06
      - arm_03_joint_05
      - arm_03_joint_04
      - arm_03_joint_03
      - arm_03_joint_02
      - arm_03_joint_01
  - name: Arm1_and_Arm2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_01_joint_06
      - arm_01_joint_05
      - arm_01_joint_04
      - arm_01_joint_03
      - arm_01_joint_02
      - arm_01_joint_01
      - arm_02_joint_06
      - arm_02_joint_05
      - arm_02_joint_04
      - arm_02_joint_03
      - arm_02_joint_02
      - arm_02_joint_01